const PREFIX = 'auth:'

export const CHANGE_MODE = `${PREFIX}CHANGE_MODE`
export const CHANGE_FIELD = `${PREFIX}CHANGE_FIELD`

export const SUBMIT_BEGIN = `${PREFIX}SUBMIT_BEGIN`
export const SUBMIT_ERROR = `${PREFIX}SUBMIT_ERROR`
export const SUBMIT_FAILURE = `${PREFIX}SUBMIT_FAILURE`
export const SUBMIT_SUCCESS = `${PREFIX}SUBMIT_SUCCESS`
