const PREFIX = 'request:'

export const CHANGE_FIELD = `${PREFIX}CHANGE_FIELD`

export const CREATE_BEGIN = `${PREFIX}CREATE_BEGIN`
export const CREATE_ERROR = `${PREFIX}CREATE_ERROR`
export const CREATE_FAILURE = `${PREFIX}CREATE_FAILURE`
export const CREATE_SUCCESS = `${PREFIX}CREATE_SUCCESS`

export const CLOSE_BEGIN = `${PREFIX}CLOSE_BEGIN`
export const CLOSE_FAILURE = `${PREFIX}CLOSE_FAILURE`
export const CLOSE_SUCCESS = `${PREFIX}CLOSE_SUCCESS`
