const PREFIX = 'users:'

export const FETCH_BEGIN = `${PREFIX}FETCH_BEGIN`
export const FETCH_FAILURE = `${PREFIX}FETCH_FAILURE`
export const FETCH_SUCCESS = `${PREFIX}FETCH_SUCCESS`

export const CHANGE_ROLE_BEGIN = `${PREFIX}CHANGE_ROLE_BEGIN`
export const CHANGE_ROLE_FAILURE = `${PREFIX}CHANGE_ROLE_FAILURE`
export const CHANGE_ROLE_SUCCESS = `${PREFIX}CHANGE_ROLE_SUCCESS`
