# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c260f84280c827841ed612df7b22f6773766771b981d15333290c2a2454522759be35b2ffd02368f30dbdda0283a1dd302c1d497c06cc8c5deb0dfe94ee2e84b

test:
  secret_key_base: 78bc4bf2b24c1bf05ba42b945f4759a73a610fcbcdf1dfb02bd3df58a3fb2067bc17590d649fcc8663146cae505535936bcdcb22ee407b4072b4149b93605a5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
